import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyOrder" model, go to https://verifly.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "DataModel-Shopify-Order",
  fields: {
    cancelReasonBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Order-cancel_reason::FieldStorageEpoch-DataModel-Shopify-Order-cancel_reason-initial",
      filterIndex: false,
    },
    currencyBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Order-currency::FieldStorageEpoch-DataModel-Shopify-Order-currency-initial",
      filterIndex: false,
    },
    financialStatusBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Order-financial_status::FieldStorageEpoch-DataModel-Shopify-Order-financial_status-initial",
      filterIndex: false,
    },
    fulfillmentStatusBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Order-fulfillment_status::FieldStorageEpoch-DataModel-Shopify-Order-fulfillment_status-initial",
      filterIndex: false,
    },
    number: {
      type: "number",
      storageKey:
        "ModelField-DataModel-Shopify-Order-number::FieldStorageEpoch-DataModel-Shopify-Order-number-initial",
      filterIndex: false,
    },
    orderNumber: {
      type: "number",
      storageKey:
        "ModelField-DataModel-Shopify-Order-order_number::FieldStorageEpoch-DataModel-Shopify-Order-order_number-initial",
      filterIndex: false,
    },
    presentmentCurrencyBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Order-presentment_currency::FieldStorageEpoch-DataModel-Shopify-Order-presentment_currency-initial",
      filterIndex: false,
    },
    statusPageUrl: {
      type: "url",
      storageKey:
        "ModelField-DataModel-Shopify-Order-__gadget_graphql_status_page_url::FieldStorageEpoch-DataModel-Shopify-Order-__gadget_graphql_status_page_url-initial",
      filterIndex: false,
    },
    verification: {
      type: "hasOne",
      child: { model: "verification", belongsToField: "order" },
      storageKey: "2nEeJNPCn05n",
    },
  },
  shopify: {
    fields: {
      additionalFees: { filterIndex: false },
      alerts: { filterIndex: false },
      billingAddress: { filterIndex: false },
      billingStatusMatchesShippingAddress: { filterIndex: false },
      browserIp: { filterIndex: false },
      businessEntity: true,
      buyerAcceptsMarketing: { filterIndex: false },
      canMarkAsPaid: { filterIndex: false },
      canNotifyCustomer: { filterIndex: false },
      cancelReason: { filterIndex: false },
      cancellation: { filterIndex: false },
      cancelledAt: { filterIndex: false },
      capturable: { filterIndex: false },
      cartDiscountAmountSet: { filterIndex: false },
      cartToken: { filterIndex: false },
      checkoutToken: { filterIndex: false },
      checkouts: true,
      clientDetails: { filterIndex: false },
      closed: { filterIndex: false },
      closedAt: { filterIndex: false },
      confirmationNumber: { filterIndex: false },
      confirmed: { filterIndex: false },
      currency: { filterIndex: false },
      currentCartDiscountAmountSet: { filterIndex: false },
      currentShippingPriceSet: { filterIndex: false },
      currentSubtotalLineItemsQuantity: { filterIndex: false },
      currentSubtotalPrice: { filterIndex: false },
      currentSubtotalPriceSet: { filterIndex: false },
      currentTotalAdditionalFeesSet: { filterIndex: false },
      currentTotalDiscounts: { filterIndex: false },
      currentTotalDiscountsSet: { filterIndex: false },
      currentTotalDutiesSet: { filterIndex: false },
      currentTotalPrice: { filterIndex: false },
      currentTotalPriceSet: { filterIndex: false },
      currentTotalTax: { filterIndex: false },
      currentTotalTaxSet: { filterIndex: false },
      currentTotalWeight: { filterIndex: false },
      customer: true,
      customerJourneySummary: { filterIndex: false },
      customerLocale: { filterIndex: false },
      discountApplications: { filterIndex: false },
      discountCodes: { filterIndex: false },
      dutiesIncluded: { filterIndex: false },
      edited: { filterIndex: false },
      email: { filterIndex: false },
      estimatedTaxes: { filterIndex: false },
      financialStatus: { filterIndex: false },
      fulfillable: { filterIndex: false },
      fulfillmentStatus: { filterIndex: false },
      fulfillmentsCount: { filterIndex: false },
      fullyPaid: { filterIndex: false },
      hasTimelineComment: { filterIndex: false },
      landingSite: { filterIndex: false },
      legacyResourceId: { filterIndex: false },
      merchantEditable: { filterIndex: false },
      merchantEditableErrors: { filterIndex: false },
      merchantOfRecordAppId: { filterIndex: false },
      name: { filterIndex: false },
      netPaymentSet: { filterIndex: false },
      note: { filterIndex: false },
      noteAttributes: { filterIndex: false },
      orderStatusUrl: { filterIndex: false },
      originalTotalAdditionalFeesSet: { filterIndex: false },
      originalTotalDutiesSet: { filterIndex: false },
      originalTotalPriceSet: { filterIndex: false },
      paymentGatewayNames: { filterIndex: false },
      phone: { filterIndex: false },
      poNumber: { filterIndex: false },
      presentmentCurrency: { filterIndex: false },
      processedAt: { filterIndex: false },
      processingMethod: { filterIndex: false },
      purchasingCompany: true,
      purchasingEntity: { filterIndex: false },
      referringSite: { filterIndex: false },
      refundDiscrepencySet: { filterIndex: false },
      refundable: { filterIndex: false },
      requiresShipping: { filterIndex: false },
      restockable: { filterIndex: false },
      returnStatus: { filterIndex: false },
      risk: { filterIndex: false },
      shippingAddress: { filterIndex: false },
      shop: true,
      shopifyCreatedAt: { filterIndex: false },
      shopifyProtect: { filterIndex: false },
      shopifyUpdatedAt: { filterIndex: false },
      sourceIdentifier: { filterIndex: false },
      sourceName: { filterIndex: false },
      sourceUrl: { filterIndex: false },
      subtotalPrice: { filterIndex: false },
      subtotalPriceSet: { filterIndex: false },
      tags: { filterIndex: false },
      taxExempt: { filterIndex: false },
      taxLines: { filterIndex: false },
      taxesIncluded: { filterIndex: false },
      test: { filterIndex: false },
      token: { filterIndex: false },
      totalCapturableSet: { filterIndex: false },
      totalCashRoundingAdjustment: { filterIndex: false },
      totalDiscounts: { filterIndex: false },
      totalDiscountsSet: { filterIndex: false },
      totalLineItemsPrice: { filterIndex: false },
      totalLineItemsPriceSet: { filterIndex: false },
      totalOutstanding: { filterIndex: false },
      totalOutstandingSet: { filterIndex: false },
      totalPrice: { filterIndex: false },
      totalPriceSet: { filterIndex: false },
      totalReceivedSet: { filterIndex: false },
      totalRefundedSet: { filterIndex: false },
      totalRefundedShippingSet: { filterIndex: false },
      totalShippingPriceSet: { filterIndex: false },
      totalTax: { filterIndex: false },
      totalTaxSet: { filterIndex: false },
      totalTipReceived: { filterIndex: false },
      totalTipReceivedSet: { filterIndex: false },
      totalWeight: { filterIndex: false },
      transactionsCount: { filterIndex: false },
      unpaid: { filterIndex: false },
    },
  },
};
