import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://verifly.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    activeRecurringSubscriptionId: {
      type: "string",
      storageKey: "4jrGjzqX09ZU",
    },
    activeUsageSubscriptionLineItemId: {
      type: "string",
      storageKey: "Lndxs9BTEbkA",
    },
    confirmationUrl: { type: "url", storageKey: "OzdyMMuyE-v6" },
    ip: { type: "string", storageKey: "bZ9Mw9SQl0K_" },
    monthlyVerificationCount: {
      type: "computed",
      sourceFile:
        "api/models/shopifyShop/monthlyVerificationCount.gelly",
      storageKey: "NnyUm2yxxy5b",
    },
    setupComplete: {
      type: "boolean",
      default: false,
      storageKey: "GhfET8UxE5RX",
    },
    testVerificationSent: {
      type: "boolean",
      default: false,
      storageKey: "Y4w_DqbwMRng",
    },
    trialStartedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "2m1dGtUcKN-c",
    },
    triggerPrice: {
      type: "number",
      default: 0,
      storageKey: "V4DqZwXgYjIg",
    },
    usedTrialMinutes: {
      type: "number",
      default: 0,
      storageKey: "uWPBJpEuZkfQ",
    },
    usedTrialMinutesUpdatedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "JpALA8Yd18LL",
    },
    verificationFlow: {
      type: "enum",
      default: "post-checkout",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["pre-checkout", "post-checkout"],
      storageKey: "1LyUyzhYhPh6",
    },
    verifications: {
      type: "hasMany",
      children: { model: "verification", belongsToField: "shop" },
      storageKey: "T1BlsuSxaDro",
    },
    verificationsEnabled: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "sY4-Srps49Qx",
    },
    veriflyPlan: {
      type: "belongsTo",
      parent: { model: "plan" },
      storageKey: "iDt0-KmUNGCo",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "appCredits",
      "appInstallations",
      "appPurchaseOneTimes",
      "appSubscriptions",
      "appUsageRecords",
      "bulkOperations",
      "checkoutApiSupported",
      "checkouts",
      "city",
      "company",
      "companyContactRoleAssignment",
      "cookieConsentLevel",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerEmail",
      "customerPaymentMethods",
      "customers",
      "domain",
      "domains",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "finances",
      "forceSsl",
      "fulfillmentServices",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orders",
      "passwordEnabled",
      "phone",
      "plan",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "primaryLocale",
      "productVariants",
      "products",
      "province",
      "provinceCode",
      "requiresExtraPaymentsAgreement",
      "setupRequired",
      "shopOwner",
      "shopifyBusinessEntity",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
