import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://verifly.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    activeRecurringSubscriptionId: {
      type: "string",
      storageKey: "4jrGjzqX09ZU",
    },
    activeUsageSubscriptionLineItemId: {
      type: "string",
      storageKey: "Lndxs9BTEbkA",
    },
    confirmationUrl: { type: "url", storageKey: "OzdyMMuyE-v6" },
    cookieConsentLevel: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-cookie_consent_level::FieldStorageEpoch-DataModel-Shopify-Shop-cookie_consent_level-initial",
    },
    currencyBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-currency::FieldStorageEpoch-DataModel-Shopify-Shop-currency-initial",
    },
    domainId: { type: "string", storageKey: "68LwaLQp0wnd" },
    eligibleForCardReaderGiveaway: {
      type: "boolean",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-eligible_for_card_reader_giveaway::FieldStorageEpoch-DataModel-Shopify-Shop-eligible_for_card_reader_giveaway-initial",
    },
    emailDomain: { type: "string", storageKey: "iQsQ9S56rXB3" },
    enabledPresentmentCurrenciesBackup: {
      type: "json",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-enabled_presentment_currencies::FieldStorageEpoch-DataModel-Shopify-Shop-enabled_presentment_currencies-initial",
    },
    enforceShippingAddressMatch: {
      type: "boolean",
      default: false,
      storageKey: "zUU2Ee0YZ8RX",
    },
    forceSsl: {
      type: "boolean",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-force_ssl::FieldStorageEpoch-DataModel-Shopify-Shop-force_ssl-initial",
    },
    ip: { type: "string", storageKey: "bZ9Mw9SQl0K_" },
    logo: {
      type: "file",
      allowPublicAccess: true,
      validations: { imagesOnly: true },
      storageKey: "dvaLoiWvNUd4",
    },
    monthlyVerificationCount: {
      type: "computed",
      sourceFile:
        "api/models/shopifyShop/monthlyVerificationCount.gelly",
      storageKey: "NnyUm2yxxy5b",
    },
    preVerificationOrderTag: {
      type: "string",
      storageKey: "WTyNZQVEg_Ie",
    },
    primaryColor: { type: "string", storageKey: "q9YeG4llwzHw" },
    secondaryColor: { type: "string", storageKey: "JNAuni7ucFIc" },
    setupComplete: {
      type: "boolean",
      default: false,
      storageKey: "GhfET8UxE5RX",
    },
    testVerificationSent: {
      type: "boolean",
      default: false,
      storageKey: "Y4w_DqbwMRng",
    },
    trialStartedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "2m1dGtUcKN-c",
    },
    triggerPrice: {
      type: "number",
      default: 0,
      storageKey: "V4DqZwXgYjIg",
    },
    usedTrialMinutes: {
      type: "number",
      default: 0,
      storageKey: "uWPBJpEuZkfQ",
    },
    usedTrialMinutesUpdatedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "JpALA8Yd18LL",
    },
    verificationFlow: {
      type: "enum",
      default: "post-checkout",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["pre-checkout", "post-checkout"],
      storageKey: "1LyUyzhYhPh6",
    },
    verifications: {
      type: "hasMany",
      children: { model: "verification", belongsToField: "shop" },
      storageKey: "T1BlsuSxaDro",
    },
    verificationsEnabled: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "sY4-Srps49Qx",
    },
    veriflyPlan: {
      type: "belongsTo",
      parent: { model: "plan" },
      storageKey: "iDt0-KmUNGCo",
    },
    weightUnitBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-weight_unit::FieldStorageEpoch-DataModel-Shopify-Shop-weight_unit-initial",
    },
  },
  shopify: {
    fields: {
      address1: true,
      address2: true,
      alerts: true,
      appCredits: true,
      appInstallations: true,
      appPurchaseOneTimes: true,
      appSubscriptions: true,
      appUsageRecords: true,
      billingAddress: true,
      bulkOperations: true,
      checkoutApiSupported: true,
      checkouts: true,
      city: true,
      company: true,
      companyContactRoleAssignment: true,
      countriesInShippingZones: true,
      country: true,
      countryCode: true,
      countryName: true,
      countyTaxes: true,
      currency: true,
      currencyFormats: true,
      customerAccounts: true,
      customerAccountsV2: true,
      customerEmail: true,
      customerPaymentMethods: true,
      customers: true,
      description: true,
      domain: true,
      domains: true,
      eligibleForPayments: true,
      email: true,
      enabledPresentmentCurrencies: true,
      finances: true,
      fulfillmentServices: true,
      gdprRequests: true,
      googleAppsDomain: true,
      googleAppsLoginEnabled: true,
      hasDiscounts: true,
      hasGiftCards: true,
      hasStorefront: true,
      ianaTimezone: true,
      latitude: true,
      longitude: true,
      marketingSmsContentEnabledAtCheckout: true,
      moneyFormat: true,
      moneyInEmailsFormat: true,
      moneyWithCurrencyFormat: true,
      moneyWithCurrencyInEmailsFormat: true,
      multiLocationEnabled: true,
      myshopifyDomain: true,
      name: true,
      orderNumberFormatPrefix: true,
      orderNumberFormatSuffix: true,
      orders: true,
      passwordEnabled: true,
      phone: true,
      plan: true,
      planDisplayName: true,
      planName: true,
      planPublicDisplayName: true,
      preLaunchEnabled: true,
      primaryLocale: true,
      productVariants: true,
      products: true,
      province: true,
      provinceCode: true,
      requiresExtraPaymentsAgreement: true,
      resourceLimits: true,
      richTextEditorUrl: true,
      setupRequired: true,
      shipsToCountries: true,
      shopAddress: true,
      shopOwner: true,
      shopifyBusinessEntity: true,
      shopifyCreatedAt: true,
      shopifyUpdatedAt: true,
      source: true,
      syncs: true,
      taxShipping: true,
      taxesIncluded: true,
      timezone: true,
      timezoneAbbreviation: true,
      timezoneOffset: true,
      timezoneOffsetMinutes: true,
      transactionalSmsDisabled: true,
      unitSystem: true,
      url: true,
      weightUnit: true,
      zipCode: true,
    },
  },
};
