import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://verifly.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    activeRecurringSubscriptionId: {
      type: "string",
      storageKey: "4jrGjzqX09ZU",
      filterIndex: false,
    },
    activeUsageSubscriptionLineItemId: {
      type: "string",
      storageKey: "Lndxs9BTEbkA",
      filterIndex: false,
    },
    confirmationUrl: {
      type: "url",
      storageKey: "OzdyMMuyE-v6",
      filterIndex: false,
    },
    cookieConsentLevel: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-cookie_consent_level::FieldStorageEpoch-DataModel-Shopify-Shop-cookie_consent_level-initial",
      filterIndex: false,
    },
    currencyBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-currency::FieldStorageEpoch-DataModel-Shopify-Shop-currency-initial",
      filterIndex: false,
    },
    domainId: {
      type: "string",
      storageKey: "68LwaLQp0wnd",
      filterIndex: false,
    },
    eligibleForCardReaderGiveaway: {
      type: "boolean",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-eligible_for_card_reader_giveaway::FieldStorageEpoch-DataModel-Shopify-Shop-eligible_for_card_reader_giveaway-initial",
      filterIndex: false,
    },
    emailDomain: {
      type: "string",
      storageKey: "iQsQ9S56rXB3",
      filterIndex: false,
    },
    enabledPresentmentCurrenciesBackup: {
      type: "json",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-enabled_presentment_currencies::FieldStorageEpoch-DataModel-Shopify-Shop-enabled_presentment_currencies-initial",
      filterIndex: false,
    },
    enforceShippingAddressMatch: {
      type: "boolean",
      default: false,
      storageKey: "zUU2Ee0YZ8RX",
      filterIndex: false,
    },
    forceSsl: {
      type: "boolean",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-force_ssl::FieldStorageEpoch-DataModel-Shopify-Shop-force_ssl-initial",
      filterIndex: false,
    },
    ip: {
      type: "string",
      storageKey: "bZ9Mw9SQl0K_",
      filterIndex: false,
    },
    logo: {
      type: "file",
      allowPublicAccess: true,
      validations: { imagesOnly: true },
      storageKey: "dvaLoiWvNUd4",
    },
    monthlyVerificationCount: {
      type: "computed",
      sourceFile:
        "api/models/shopifyShop/monthlyVerificationCount.gelly",
      storageKey: "NnyUm2yxxy5b",
    },
    preVerificationOrderTag: {
      type: "string",
      storageKey: "WTyNZQVEg_Ie",
      filterIndex: false,
    },
    primaryColor: {
      type: "string",
      storageKey: "q9YeG4llwzHw",
      filterIndex: false,
    },
    secondaryColor: {
      type: "string",
      storageKey: "JNAuni7ucFIc",
      filterIndex: false,
    },
    setupComplete: {
      type: "boolean",
      default: false,
      storageKey: "GhfET8UxE5RX",
      filterIndex: false,
    },
    testVerificationSent: {
      type: "boolean",
      default: false,
      storageKey: "Y4w_DqbwMRng",
      filterIndex: false,
    },
    trialStartedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "2m1dGtUcKN-c",
      filterIndex: false,
    },
    triggerPrice: {
      type: "number",
      default: 0,
      storageKey: "V4DqZwXgYjIg",
      filterIndex: false,
    },
    usedTrialMinutes: {
      type: "number",
      default: 0,
      storageKey: "uWPBJpEuZkfQ",
      filterIndex: false,
    },
    usedTrialMinutesUpdatedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "JpALA8Yd18LL",
      filterIndex: false,
    },
    verificationFlow: {
      type: "enum",
      default: "post-checkout",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["pre-checkout", "post-checkout"],
      storageKey: "1LyUyzhYhPh6",
      filterIndex: false,
    },
    verifications: {
      type: "hasMany",
      children: { model: "verification", belongsToField: "shop" },
      storageKey: "T1BlsuSxaDro",
    },
    verificationsEnabled: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "sY4-Srps49Qx",
      filterIndex: false,
    },
    veriflyPlan: {
      type: "belongsTo",
      parent: { model: "plan" },
      storageKey: "iDt0-KmUNGCo",
    },
    verifyRepeatCustomers: {
      type: "boolean",
      default: false,
      storageKey: "eGQQaPTEyrCS",
      filterIndex: false,
    },
    weightUnitBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-weight_unit::FieldStorageEpoch-DataModel-Shopify-Shop-weight_unit-initial",
      filterIndex: false,
    },
  },
  shopify: {
    fields: {
      address1: { filterIndex: false },
      address2: { filterIndex: false },
      alerts: { filterIndex: false },
      appCredits: true,
      appInstallations: true,
      appPurchaseOneTimes: true,
      appSubscriptions: true,
      appUsageRecords: true,
      billingAddress: { filterIndex: false },
      bulkOperations: true,
      checkoutApiSupported: { filterIndex: false },
      checkouts: true,
      city: { filterIndex: false },
      company: true,
      companyContactRoleAssignment: true,
      countriesInShippingZones: { filterIndex: false },
      country: { filterIndex: false },
      countryCode: { filterIndex: false },
      countryName: { filterIndex: false },
      countyTaxes: { filterIndex: false },
      currency: { filterIndex: false },
      currencyFormats: { filterIndex: false },
      customerAccounts: { filterIndex: false },
      customerAccountsV2: { filterIndex: false },
      customerEmail: { filterIndex: false },
      customerPaymentMethods: true,
      customers: true,
      description: { filterIndex: false },
      domain: { filterIndex: false },
      domains: true,
      eligibleForPayments: { filterIndex: false },
      email: { filterIndex: false },
      enabledPresentmentCurrencies: { filterIndex: false },
      finances: { filterIndex: false },
      fulfillmentServices: true,
      gdprRequests: true,
      googleAppsDomain: { filterIndex: false },
      googleAppsLoginEnabled: { filterIndex: false },
      hasDiscounts: { filterIndex: false },
      hasGiftCards: { filterIndex: false },
      hasStorefront: { filterIndex: false },
      ianaTimezone: { filterIndex: false },
      latitude: { filterIndex: false },
      longitude: { filterIndex: false },
      marketingSmsContentEnabledAtCheckout: { filterIndex: false },
      moneyFormat: { filterIndex: false },
      moneyInEmailsFormat: { filterIndex: false },
      moneyWithCurrencyFormat: { filterIndex: false },
      moneyWithCurrencyInEmailsFormat: { filterIndex: false },
      multiLocationEnabled: { filterIndex: false },
      myshopifyDomain: true,
      name: { filterIndex: false },
      orderNumberFormatPrefix: { filterIndex: false },
      orderNumberFormatSuffix: { filterIndex: false },
      orders: true,
      passwordEnabled: { filterIndex: false },
      phone: { filterIndex: false },
      plan: { filterIndex: false },
      planDisplayName: true,
      planName: true,
      planPublicDisplayName: { filterIndex: false },
      preLaunchEnabled: { filterIndex: false },
      primaryLocale: { filterIndex: false },
      productVariants: true,
      products: true,
      province: { filterIndex: false },
      provinceCode: { filterIndex: false },
      requiresExtraPaymentsAgreement: { filterIndex: false },
      resourceLimits: { filterIndex: false },
      richTextEditorUrl: { filterIndex: false },
      setupRequired: { filterIndex: false },
      shipsToCountries: { filterIndex: false },
      shopAddress: { filterIndex: false },
      shopOwner: { filterIndex: false },
      shopifyBusinessEntity: true,
      shopifyCreatedAt: { filterIndex: false },
      shopifyUpdatedAt: { filterIndex: false },
      source: { filterIndex: false },
      syncs: true,
      taxShipping: { filterIndex: false },
      taxesIncluded: { filterIndex: false },
      timezone: { filterIndex: false },
      timezoneAbbreviation: { filterIndex: false },
      timezoneOffset: { filterIndex: false },
      timezoneOffsetMinutes: { filterIndex: false },
      transactionalSmsDisabled: { filterIndex: false },
      unitSystem: { filterIndex: false },
      url: { filterIndex: false },
      weightUnit: { filterIndex: false },
      zipCode: { filterIndex: false },
    },
  },
};
