import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyCheckout" model, go to https://verifly.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "DataModel-Shopify-Checkout",
  fields: {
    shippingLine: {
      type: "json",
      storageKey:
        "ModelField-DataModel-Shopify-Checkout-shipping_line::FieldStorageEpoch-DataModel-Shopify-Checkout-shipping_line-initial",
    },
  },
  shopify: {
    fields: {
      abandonedCheckoutUrl: true,
      appliedDiscount: true,
      buyerAcceptsMarketing: true,
      completedAt: true,
      creditCard: true,
      currency: true,
      customer: true,
      customerLocale: true,
      device: true,
      discountCode: true,
      discountCodes: true,
      email: true,
      legalNoticeUrl: true,
      name: true,
      note: true,
      noteAttributes: true,
      order: true,
      orderStatusUrl: true,
      paymentDue: true,
      paymentUrl: true,
      payments: true,
      phone: true,
      presentmentCurrency: true,
      privacyPolicyUrl: true,
      refundPolicyUrl: true,
      requiresShipping: true,
      reservationTime: true,
      reservationTimeLeft: true,
      shippingLines: true,
      shippingPolicyUrl: true,
      shop: true,
      shopifyCreatedAt: true,
      shopifyPaymentsAccountId: true,
      shopifyUpdatedAt: true,
      sourceIdentifier: true,
      sourceName: true,
      sourceUrl: true,
      subscriptionPolicyUrl: true,
      subtotalPrice: true,
      taxExempt: true,
      taxLines: true,
      taxManipulations: true,
      taxesIncluded: true,
      termsOfSaleUrl: true,
      termsOfServiceUrl: true,
      token: true,
      totalLineItemsPrice: true,
      totalPrice: true,
      totalTax: true,
      totalTipReceived: true,
      userId: true,
      webUrl: true,
    },
  },
};
