import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyCheckout" model, go to https://verifly.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "DataModel-Shopify-Checkout",
  fields: {
    shippingLine: {
      type: "json",
      storageKey:
        "ModelField-DataModel-Shopify-Checkout-shipping_line::FieldStorageEpoch-DataModel-Shopify-Checkout-shipping_line-initial",
      filterIndex: false,
      searchIndex: false,
    },
  },
  searchIndex: false,
  shopify: {
    fields: {
      abandonedCheckoutUrl: {
        filterIndex: false,
        searchIndex: false,
      },
      appliedDiscount: { filterIndex: false, searchIndex: false },
      buyerAcceptsMarketing: {
        filterIndex: false,
        searchIndex: false,
      },
      completedAt: { filterIndex: false, searchIndex: false },
      creditCard: { filterIndex: false, searchIndex: false },
      currency: { filterIndex: false, searchIndex: false },
      customer: { searchIndex: false },
      customerLocale: { filterIndex: false, searchIndex: false },
      device: { filterIndex: false, searchIndex: false },
      discountCode: { filterIndex: false, searchIndex: false },
      discountCodes: { filterIndex: false, searchIndex: false },
      email: { filterIndex: false, searchIndex: false },
      legalNoticeUrl: { filterIndex: false, searchIndex: false },
      name: { filterIndex: false, searchIndex: false },
      note: { filterIndex: false, searchIndex: false },
      noteAttributes: { filterIndex: false, searchIndex: false },
      order: { searchIndex: false },
      orderStatusUrl: { filterIndex: false, searchIndex: false },
      paymentDue: { filterIndex: false, searchIndex: false },
      paymentUrl: { filterIndex: false, searchIndex: false },
      payments: { filterIndex: false, searchIndex: false },
      phone: { filterIndex: false, searchIndex: false },
      presentmentCurrency: { filterIndex: false, searchIndex: false },
      privacyPolicyUrl: { filterIndex: false, searchIndex: false },
      refundPolicyUrl: { filterIndex: false, searchIndex: false },
      requiresShipping: { filterIndex: false, searchIndex: false },
      reservationTime: { filterIndex: false, searchIndex: false },
      reservationTimeLeft: { filterIndex: false, searchIndex: false },
      shippingLines: { filterIndex: false, searchIndex: false },
      shippingPolicyUrl: { filterIndex: false, searchIndex: false },
      shop: { searchIndex: false },
      shopifyCreatedAt: { filterIndex: false, searchIndex: false },
      shopifyPaymentsAccountId: {
        filterIndex: false,
        searchIndex: false,
      },
      shopifyUpdatedAt: { filterIndex: false, searchIndex: false },
      sourceIdentifier: { filterIndex: false, searchIndex: false },
      sourceName: { filterIndex: false, searchIndex: false },
      sourceUrl: { filterIndex: false, searchIndex: false },
      subscriptionPolicyUrl: {
        filterIndex: false,
        searchIndex: false,
      },
      subtotalPrice: { filterIndex: false, searchIndex: false },
      taxExempt: { filterIndex: false, searchIndex: false },
      taxLines: { filterIndex: false, searchIndex: false },
      taxManipulations: { filterIndex: false, searchIndex: false },
      taxesIncluded: { filterIndex: false, searchIndex: false },
      termsOfSaleUrl: { filterIndex: false, searchIndex: false },
      termsOfServiceUrl: { filterIndex: false, searchIndex: false },
      token: { searchIndex: false },
      totalLineItemsPrice: { filterIndex: false, searchIndex: false },
      totalPrice: { filterIndex: false, searchIndex: false },
      totalTax: { filterIndex: false, searchIndex: false },
      totalTipReceived: { filterIndex: false, searchIndex: false },
      userId: { filterIndex: false, searchIndex: false },
      webUrl: { filterIndex: false, searchIndex: false },
    },
  },
};
